image: 
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - Any CPU

configuration:
  - Release

build_script:
  - mkdir build
  - cd build
  - cmake .. -DINTERPRETER_TESTS:BOOL=TRUE
  - cmake --build . --config Release

test_script:
  - .\Release\Interpreter-Tests.exe
