image: 
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - Any CPU

configuration:
  - Debug

build_script:
  - mkdir build
  - cd build
  - cmake .. -DINTERPRETER_TESTS:BOOL=TRUE
  - cmake --build . --config Debug

test_script:
  - .\Debug\Interpreter-Tests.exe
