dist: trusty
sudo: false
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew update && brew install gcc5 && CC=gcc-5 && CXX=g++-5"
    - os: linux
      compiler: clang
    - os: osx
      compiler: clang

before_install:
  - mkdir build
  - cd build
  - eval "${MATRIX_EVAL}"

install:
  - cmake .. -DINTERPRETER_TESTS:BOOL=TRUE
  - cmake --build .

script:
  - ./Interpreter-Tests
