dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

script:
  - mkdir build
  - cd build
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake .. -DINTERPRETER_TESTS:BOOL=TRUE
  - cmake --build ..
  - cd ..
  - ls
  - ls /build
