dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

script:
  - CXX=/usr/bin/clang++-5.0 CC=/usr/bin/clang-5.0 cmake . -DINTERPRETER_TESTS:BOOL=TRUE
  - cmake --build .
  - ls
  - ls /build
